services:
  rust:
    build: .
    image: idelchi/rust:latest
    container_name: rust
    volumes:
      - ${GODYL_OUTPUT_DIR}:/home/user/binaries
    working_dir: /home/user/ws
    network_mode: none
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        cp /opt/rust/bin/* /home/user/binaries/
